server:
  port: 8888
  address: 172.20.10.2

spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hat;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:sqlmap/**/*.xml
  config-location: classpath:mybatis-config.xml

kakao:
  secret:
    map:
      key: f103fa2bf8d6ac153ef15b65d9a9589a

google:
  secret:
    map:
      key: AIzaSyCIxd8vZJbsaNe6RuoWdluwVNKEjxscdis
    user:
      key: AIzaSyCuKTD2RFLzb-ILD4NuqpqYvDClhZMibLg
      client: 143425051091-tajs1p4dpmuoa9aslqunl3t6gdt77esv.apps.googleusercontent.com
      password: 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